### ISSUE TITLE
Checklist de infraestrutura

### ISSUE THREAD

**Issue by Dayof** [pyladiesdf/DjangoGirls#20]
- [ ] 1 switch (Ulisses)
- [ ] 5 roteadores (@BrunaNayara , @fabiommendes, @joenio, @dayof, Ulisses)
- [ ] 15 a 20 extensões (?) (Todas tutoras + organizadores)
- [ ] 5 computadores preparados para utilização das participantes (computadores da unb gama)
- [ ] 1 servidor preparado para servir localmente o gitbook #4  (computador da unb)
- [ ] 5 pendrives com arquivos de instalação #5 (organizadores ?)
- [ ] 5 cabos de 5 metros
- [ ] 10 cabos de 1,5 metros
- [ ] 1 caixa ou alguns metros de cabo e conectores RJ45 para usar no dia de montar o lab
- [ ] 1 estabilizador para o switch
- [x] 1 caixa de som amplificada (utilizaremos a caixa do Lappis)
- [ ] 1 microfone
- [ ] projetor (@Heloisecs irá emprestar um no dia do evento)

Algo mais ?

**Comment by Dayof** [comment]
@fabiommendes e @joenio podem checar se falta algo nesta lista ?

**Comment by joenio** [comment]
@Dayof a lista está revisada.

falta agora coletar os equipamentos, mas como a maioria será emprestado vamos deixar para fazer isso mais próximo da data do primeiro DG interno.
